on:
  pull_request:
    branches: [ main ]

jobs:
  lint_verify:
    name: Run linter checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run ktlint Linter
        run: ./gradlew ktlintCheck

      - name: Run Android Linter
        run: ./gradlew lintRelease
